name: cellpose-tracking
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-image
  - scipy
  - tifffile
  - pytorch
  - torchvision
  - cpuonly
  - jupyterlab
  - pip
  - pip:
      - cellpose
      - opencv-python